version: '3.9'

services:
  eureka:
    container_name: eureka
    restart: always
    build: ./Eureka
    ports:
      - "8761:8761"

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"

    command: --config /etc/mongo/mongod.conf #&& mongo /docker-entrypoint-initdb.d/mongo-init.js

    volumes:
      - ./mongo/mongod.conf:/etc/mongo/mongod.conf
      - ./CV_Processing/secrets/cert_key.pem:/etc/mongo/cert_key.pem
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo/mongodb:/var/lib/mongodb:rw

  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: 'bitnami/elasticsearch:latest'
    ports:
      - "9200:9200"
    environment:
      ELASTICSEARCH_PORT_NUMBER: 9200
      ELASTICSEARCH_DATA_DIR_LIST: /elasticsearch/data

    volumes:
      - ./elasticsearch/data:/elasticsearch/data:rw

  gateway:
    container_name: gateway
    restart: always
    build: ./Gateway
    depends_on:
      - eureka
    ports:
      - "8000:8000"
    environment:
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761

  orchestrator:
    container_name: orchestrator
    restart: always
    build: ./Orchestrator
    depends_on:
      - eureka
    ports:
      - "8001:8001"
    environment:
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761

  authentication:
    container_name: authentication
    restart: always
    build: ./Authentication
    depends_on:
      - eureka
      - mongo
    ports:
      - "8002:8002"
    environment:
      DB_HOST: mongo
      #DB_HOST: host.docker.internal
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761

  cv-processing:
    container_name: cv-processing
    restart: always
    build: ./CV_Processing
    depends_on:
      - eureka
      - mongo
    ports:
      - "8003:8003"
    environment:
      DB_HOST: mongo
      #DB_HOST: host.docker.internal
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761

  job-posting:
    container_name: job-posting
    restart: always
    build: ./Job_Posting
    depends_on:
      - eureka
      - mongo
    ports:
      - "8004:8004"
    environment:
      DB_HOST: mongo
      #DB_HOST: host.docker.internal
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761

  search:
    container_name: search
    restart: always
    build: ./Search
    depends_on:
      - elasticsearch
      - eureka
      - mongo
    ports:
      - "8005:8005"
    environment:
      DB_HOST: mongo
      #DB_HOST: host.docker.internal
      #ELASTIC_HOST: host.docker.internal
      ELASTIC_HOST: elasticsearch
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761

  recommendation:
    container_name: recommendation
    restart: always
    build: ./Recommendation
    depends_on:
      - eureka
      - mongo
    ports:
      - "8006:8006"
    environment:
      DB_HOST: mongo
      #DB_HOST: host.docker.internal
      EUREKA_URL_DEFAULT_ZONE: http://eureka:8761/eureka
      EUREKA_URL: http://eureka:8761